# Generated by Django 3.2.8 on 2021-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter genre (e.g. Survival): ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of files included.', max_length=1000)),
                ('genre', models.ManyToManyField(help_text='Select a genre for this SD card', to='webstore.Genre')),
            ],
        ),
    ]
