# Generated by Django 3.2.8 on 2021-10-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of this item.', max_length=1000)),
                ('sdcard_included', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ZimFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of files included.', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='sdcard',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
