# Generated by Django 3.2.8 on 2021-10-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_auto_20211015_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sdcard',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zimfile',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='sdcard_included',
        ),
        migrations.AlterField(
            model_name='sdcard',
            name='description',
            field=models.TextField(help_text='Enter a brief description of this item.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='zimfile',
            name='description',
            field=models.TextField(help_text='Enter a brief description of this item.', max_length=1000),
        ),
    ]
