# Generated by Django 3.2.8 on 2021-10-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_auto_20211015_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZimFile',
            new_name='Download',
        ),
    ]
